[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm build:railway"

[deploy]
startCommand = "pnpm start"

[env]
PORT = "3000"
DISABLE_ESLINT_PLUGIN = "true"
NODE_OPTIONS = "--max-old-space-size=4096"
NEXT_IGNORE_TYPE_CHECK = "true"

# Frontend service
[[services]]
name = "frontend"
envVarGroup = "frontend"
healthcheckPath = "/"
buildCommand = "DISABLE_ESLINT_PLUGIN=true pnpm install && pnpm build:railway"
startCommand = "pnpm start"

# Environment variables for frontend
[services.frontend.env]
NEXT_PUBLIC_API_URL = "${{RAILWAY_SERVICE_SERVER_URL}}"

# Backend service
[[services]]
name = "server"
rootDirectory = "server"
envVarGroup = "server"
healthcheckPath = "/"
buildCommand = "pnpm install && pnpm build"
startCommand = "pnpm start"

# Environment variables for server
[services.server.env]
LIVEKIT_URL = "${{LIVEKIT_URL}}"
LIVEKIT_API_KEY = "${{LIVEKIT_API_KEY}}"
LIVEKIT_API_SECRET = "${{LIVEKIT_API_SECRET}}"
PORT = "3000" 